Repository input-output-hk/catalyst-core, pull requests merged in 2022-11, with the labels that each got.

#48 Javascript tests for wallet-js wasm bindings
  src/chain-wallet-libs/bindings/wallet-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-js/README.md
  src/chain-wallet-libs/bindings/wallet-js/js-test/.gitignore
  src/chain-wallet-libs/bindings/wallet-js/js-test/README.md
  src/chain-wallet-libs/bindings/wallet-js/js-test/bootstrap.js
  src/chain-wallet-libs/bindings/wallet-js/js-test/index.html
  src/chain-wallet-libs/bindings/wallet-js/js-test/index.js
  src/chain-wallet-libs/bindings/wallet-js/js-test/package.json
  src/chain-wallet-libs/bindings/wallet-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-js/js-test/webpack.config.js
Labels: review me

#42 implemented all snapshot related endpoints in mock
  src/vit-servicing-station/vit-servicing-station-lib/src/utils/serde.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/challenges/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
  src/vit-testing/vitup/src/config/static_data/current.rs
  src/vit-testing/vitup/src/mode/mock/context.rs
  src/vit-testing/vitup/src/mode/mock/farm/rest/mod.rs
  src/vit-testing/vitup/src/mode/mock/rest/admin.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/handlers.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/mod.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/routes.rs
  src/vit-testing/vitup/src/mode/mock/rest/cors.rs
  src/vit-testing/vitup/src/mode/mock/rest/mod.rs
  src/vit-testing/vitup/src/mode/mock/rest/node/handlers.rs
  src/vit-testing/vitup/src/mode/mock/rest/node/mod.rs
  src/vit-testing/vitup/src/mode/mock/rest/ssl.rs
  src/vit-testing/vitup/src/mode/mock/rest/vit_ss.rs
  src/vit-testing/vitup/src/mode/mock/snapshot.rs
Labels: review me

#53 NPG-3383 Add Postgres support to vit-ss
  Cargo.lock
  src/vit-servicing-station/.env
  src/vit-servicing-station/diesel.toml
  src/vit-servicing-station/vit-servicing-station-cli/src/csv/loaders.rs
  src/vit-servicing-station/vit-servicing-station-lib/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-lib/migrations/2020-05-22-112032_setup_db/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/00000000000000_diesel_initial_setup/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/00000000000000_diesel_initial_setup/up.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/2022-11-03-210841_setup_db/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/2022-11-03-210841_setup_db/up.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/sqlite/2020-05-22-112032_setup_db/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/sqlite/2020-05-22-112032_setup_db/up.sql
  src/vit-servicing-station/vit-servicing-station-lib/src/db/migrations.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/api_tokens.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/challenges.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/community_advisors_reviews.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/funds.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/proposals.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/vote.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/voteplans.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/api_tokens.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/challenges.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/community_advisors_reviews.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/funds.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/goals.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/groups.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/proposals.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/search/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/voteplans.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/votes.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/schema.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/lib.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/testing/filters.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/api_token.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/context.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/funds/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/health/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/service_version/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/votes/handlers.rs
Labels: review me

#56 Npg 3628 refactor explorer error handling
  Cargo.lock
  src/jormungandr/explorer/src/db/error.rs
  src/jormungandr/explorer/src/db/indexing.rs
  src/jormungandr/explorer/src/db/mod.rs
  src/jormungandr/explorer/src/db/persistent_sequence.rs
  src/jormungandr/explorer/src/main.rs
Labels: review me

#59 Update nix flake
  flake.lock
  flake.nix
Labels: review me

#62 NPG-3846 Add OpenTelemetry layer to jormungandr
  Cargo.lock
  src/jormungandr/jormungandr/Cargo.toml
  src/jormungandr/jormungandr/src/lib.rs
  src/jormungandr/jormungandr/src/settings/command_arguments.rs
  src/jormungandr/jormungandr/src/settings/logging.rs
  src/jormungandr/jormungandr/src/settings/start/config.rs
  src/jormungandr/jormungandr/src/settings/start/mod.rs
  src/jormungandr/jormungandr/src/utils/task.rs
Labels: review me

#63 Update top-level script to build/test/install everything in the monorepo
  install-all.sh
Labels: review me

#69 Embed vit-ss migration files
  src/vit-servicing-station/vit-servicing-station-cli/src/api_token.rs
  src/vit-servicing-station/vit-servicing-station-cli/src/init_db.rs
  src/vit-servicing-station/vit-servicing-station-lib/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-lib/src/db/migrations.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/api_tokens.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/testing/filters.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/api_token.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/funds/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/proposals/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/votes/handlers.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/paths.rs
Labels: review me

#79 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: review me

#41 Add simple soak test for mock and protect its execution by soak feature
  src/vit-testing/vitup/Cargo.toml
  src/vit-testing/vitup/src/client/rest.rs
  src/vit-testing/vitup/tests/mock/mod.rs
  src/vit-testing/vitup/tests/mock/soak.rs
  src/vit-testing/vitup/tests/mock/startup.rs
Labels: review me

#86 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: review me

#91 Fixes the API Docs, Adds the Contributing guide and adds VIT-SS docs
  book/src/CONTRIBUTING.md
  book/src/SUMMARY.md
  book/src/api/vit-servicing-station-v0.md
  book/src/api/vit-testing-v0.md
  book/src/api/vote-ledger-v0.md
  book/src/api/vote-ledger-v1.md
  book/src/core-vitss-doc/api/v0.yaml
  book/src/core-vitss-doc/testing.md
Labels: documentation

#99 Docs ci
  .github/workflows/gh-pages.yml
Labels: documentation, review me

#57 Archiving vit-ss database data into csv files
  Cargo.lock
  src/catalyst-toolbox/catalyst-toolbox/src/archive/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/archive/node.rs
  src/catalyst-toolbox/catalyst-toolbox/src/archive/vit_ss.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/archive/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/archive/node.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/archive/vit_ss.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/funds.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/snapshot.rs
Labels: review me

#100 Fix explorer block tests
  src/jormungandr/testing/jormungandr-automation/src/jcli/api/rest/v0/block.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/all_blocks_verifier.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/block_by_id_verifier.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/blocks_by_chain_length_verifier.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/explorer/verifiers/last_block_verifier.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/block.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/leadership.rs
Labels: review me

#90 Stop checking for SQLite db file when using Postgres in vit-ss server and vit-ss CLI
  src/vit-servicing-station/vit-servicing-station-cli/src/api_token.rs
  src/vit-servicing-station/vit-servicing-station-cli/src/db_utils.rs
  src/vit-servicing-station/vit-servicing-station-server/src/main.rs
Labels: review me

#103 Add search_count method to mock
  src/vit-testing/vitup/src/mode/mock/rest/mod.rs
  src/vit-testing/vitup/src/mode/mock/rest/search.rs
  src/vit-testing/vitup/tests/mock/soak.rs
Labels: review me

#105 search API extensions
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/explorer/block.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/search/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/search/logic.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/search/requests.rs
  src/vit-testing/vitup/src/mode/mock/rest/search.rs
Labels: review me

#101 Implement postgres support for vit ss integration tests
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/utils/collections.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/utils/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/db/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/load/rest.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/paths.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/startup/db.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/startup/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/bootstrap/arguments/block0.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/bootstrap/arguments/in_settings.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/bootstrap/arguments/out_settings.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/bootstrap/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/advisor_reviews.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/challenges.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/cors.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/funds.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/genesis.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/proposals.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/service_version.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/token.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/voteplan_id.rs
  src/vit-testing/vitup/src/cli/validate/ideascale.rs
  src/vit-testing/vitup/src/mode/standard/controllers/main.rs
  src/vit-testing/vitup/src/mode/standard/controllers/vit_station/data.rs
Labels: review me

#108 Npg 3284 explorer networking tests
  src/jormungandr/testing/jormungandr-integration-tests/src/networking/explorer.rs
Labels: review me
