Repository input-output-hk/catalyst-core, pull requests merged in 2022-12, with the labels that each got.

#116 Remove redundant explorer tests
  src/jormungandr/explorer/src/main.rs
  src/jormungandr/explorer/src/tests.rs
Labels: review me

#117 mock search API
  src/vit-testing/vitup/src/mode/mock/rest/search.rs
Labels: review me

#125 Wallet Javascript bindings, singVotes function
  .github/workflows/ci_tests.yml
  Cargo.lock
  src/chain-libs/chain-impl-mockchain/src/key.rs
  src/chain-libs/chain-time/src/era.rs
  src/chain-libs/chain-time/src/timeframe.rs
  src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
  src/chain-wallet-libs/bindings/wallet-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-js/js-test/package.json
  src/chain-wallet-libs/bindings/wallet-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-js/js/README.md
  src/chain-wallet-libs/bindings/wallet-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-js/js/package.json
  src/chain-wallet-libs/bindings/wallet-js/src/lib.rs
  src/chain-wallet-libs/wallet/Cargo.toml
  src/chain-wallet-libs/wallet/src/blockchain.rs
  src/jormungandr/jormungandr-lib/src/crypto/hash.rs
  src/jormungandr/jormungandr-lib/src/crypto/serde.rs
  src/jormungandr/jormungandr-lib/src/interfaces/block0_date.rs
  src/jormungandr/jormungandr-lib/src/interfaces/mod.rs
  src/jormungandr/jormungandr-lib/src/interfaces/time_era.rs
  src/jormungandr/testing/jormungandr-automation/src/jcli/services/fragment_check.rs
  src/jormungandr/testing/loki/src/sender.rs
Labels: review me

#122 Add `extra` field to Proposal model
  Cargo.lock
  book/src/core-vitss-doc/api/v0.yaml
  src/vit-servicing-station/vit-servicing-station-cli/src/csv/models.rs
  src/vit-servicing-station/vit-servicing-station-lib/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/2022-11-29-134506_add_proposals_extra_fields/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/postgres/2022-11-29-134506_add_proposals_extra_fields/up.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/sqlite/2022-11-29-134506_add_proposals_extra_fields/down.sql
  src/vit-servicing-station/vit-servicing-station-lib/migrations/sqlite/2022-11-29-134506_add_proposals_extra_fields/up.sql
  src/vit-servicing-station/vit-servicing-station-lib/src/db/migrations.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/models/proposals.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/queries/search/mod.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/schema.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/db/views_schema.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/data/generator/arbitrary/snapshot_generator.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/data/generator/voting/generator.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/db/mod.rs
Labels: review me

#124 Voting tools signature verification adjustment.
  Cargo.lock
  src/vit-testing/mainnet-lib/src/lib.rs
  src/vit-testing/mainnet-lib/src/wallet/mod.rs
  src/vit-testing/mainnet-lib/src/wallet/registration.rs
  src/voting-tools-rs/Cargo.toml
  src/voting-tools-rs/src/logic.rs
  src/voting-tools-rs/src/testing/functional/mod.rs
Labels: bug, review me

#80 Automation for search service
  Cargo.lock
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/search/requests.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/path.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/raw.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/search.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/bootstrap/arguments/logger.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/search.rs
  src/vit-testing/vitup/Cargo.toml
Labels: review me

#102 Snapshot wormhole
  Cargo.lock
  book/src/core-testing-doc/introduction.md
  book/src/core-testing-doc/snapshot-wormhole/configuration.md
  book/src/core-testing-doc/snapshot-wormhole/introduction.md
  src/jortestkit/src/process/wait.rs
  src/vit-testing/integration-tests/src/component/registration/local.rs
  src/vit-testing/mainnet-tools/Cargo.toml
  src/vit-testing/mainnet-tools/src/bin/cardano-cli-mock.rs
  src/vit-testing/mainnet-tools/src/bin/snapshot-wormhole.rs
  src/vit-testing/mainnet-tools/src/bin/voter-registration-mock.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/command/address.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/command/mod.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/command/query.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/command/stake_address.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/command/transaction.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/fake.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/mod.rs
  src/vit-testing/mainnet-tools/src/lib.rs
  src/vit-testing/mainnet-tools/src/network/mod.rs
  src/vit-testing/mainnet-tools/src/snapshot_wormhole/command.rs
  src/vit-testing/mainnet-tools/src/snapshot_wormhole/config.rs
  src/vit-testing/mainnet-tools/src/snapshot_wormhole/mod.rs
  src/vit-testing/mainnet-tools/src/voter_registration/command.rs
  src/vit-testing/mainnet-tools/src/voter_registration/fake.rs
  src/vit-testing/mainnet-tools/src/voter_registration/mod.rs
  src/vit-testing/mainnet-tools/src/voting_tools/mod.rs
  src/vit-testing/scheduler-service-lib/Cargo.toml
  src/vit-testing/scheduler-service-lib/src/client/rest.rs
  src/vit-testing/snapshot-trigger-service/Cargo.toml
  src/vit-testing/snapshot-trigger-service/src/client/mod.rs
  src/vit-testing/snapshot-trigger-service/src/client/rest.rs
  src/vit-testing/snapshot-trigger-service/src/lib.rs
  src/voting-tools-rs/src/bin/snapshot_tool.rs
  src/voting-tools-rs/src/logic.rs
Labels: review me

#137 Add typings for wallet Javascript bindings
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
Labels: enhancement, review me

#140 fix hex-encoded string conversion for chain_proposal_id
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/dreps.rs
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/voters.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/data/generator/arbitrary/snapshot_generator.rs
Labels: review me

#141 Add documentation about VoteCast transaction structure
  src/chain-libs/chain-impl-mockchain/doc/format.abnf
  src/chain-libs/chain-impl-mockchain/doc/format.md
  src/chain-libs/chain-impl-mockchain/src/fragment/mod.rs
Labels: review me

#143 add information about chain_proposal_id field
  book/src/core-ledger-doc/advanced/04_vote_fragments_voteplan_blockchain_relationships.md
Labels: review me

#142 Fix /snapshot/raw_snapshot/{tag} voting_power_cap serialization bug
  src/vit-servicing-station/vit-servicing-station-lib/src/utils/serde.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
Labels: review me

#149 Add feature template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: review me

#148 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: review me

#152 Remove unused bip39 crate
  Cargo.lock
  Cargo.toml
  src/chain-wallet-libs/bindings/wallet-c/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-core/Cargo.toml
  src/chain-wallet-libs/bip39/Cargo.toml
  src/chain-wallet-libs/bip39/LICENSE-APACHE
  src/chain-wallet-libs/bip39/LICENSE-MIT
  src/chain-wallet-libs/bip39/config.toml
  src/chain-wallet-libs/bip39/src/bip39_chinese_simplified.txt
  src/chain-wallet-libs/bip39/src/bip39_chinese_traditional.txt
  src/chain-wallet-libs/bip39/src/bip39_english.txt
  src/chain-wallet-libs/bip39/src/bip39_french.txt
  src/chain-wallet-libs/bip39/src/bip39_italian.txt
  src/chain-wallet-libs/bip39/src/bip39_japanese.txt
  src/chain-wallet-libs/bip39/src/bip39_korean.txt
  src/chain-wallet-libs/bip39/src/bip39_spanish.txt
  src/chain-wallet-libs/bip39/src/bits.rs
  src/chain-wallet-libs/bip39/src/dictionary.rs
  src/chain-wallet-libs/bip39/src/entropy.rs
  src/chain-wallet-libs/bip39/src/error.rs
  src/chain-wallet-libs/bip39/src/lib.rs
  src/chain-wallet-libs/bip39/src/mnemonic.rs
  src/chain-wallet-libs/bip39/src/seed.rs
  src/chain-wallet-libs/bip39/src/test_vectors/bip39_english.txt
  src/chain-wallet-libs/bip39/src/test_vectors/bip39_japanese.txt
  src/chain-wallet-libs/bip39/src/types.rs
  src/chain-wallet-libs/hdkeygen/Cargo.toml
  src/chain-wallet-libs/wallet/Cargo.toml
Labels: review me

#150 Clean up ci_tests.yml
  .github/workflows/ci_tests.yml
Labels: review me

#146 Update Javascript wallet bindings, replace wallet approach with the basic transaction building
  src/catalyst-toolbox/catalyst-toolbox/src/recovery/tally.rs
  src/chain-libs/chain-impl-mockchain/src/accounting/account/mod.rs
  src/chain-libs/chain-impl-mockchain/src/accounting/account/spending.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  src/chain-libs/chain-impl-mockchain/src/testing/data/address.rs
  src/chain-wallet-libs/bindings/wallet-core/src/lib.rs
  src/chain-wallet-libs/bindings/wallet-core/src/tx_builder.rs
  src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/certificates/vote_plan.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/utils.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/tests/lib.rs
  src/chain-wallet-libs/wallet/src/account.rs
  src/chain-wallet-libs/wallet/src/lib.rs
  src/chain-wallet-libs/wallet/src/transaction/builder.rs
  src/chain-wallet-libs/wallet/tests/account.rs
  src/jormungandr/jcli/src/jcli_lib/transaction/mk_witness.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/transaction/witness.rs
Labels: review me

#128 Add build.yml
  .github/workflows/build.yml
  .github/workflows/ci_tests.yml
Labels: review me

#167 build: adds Nix CI
  .github/workflows/nix.yml
  flake.lock
  flake.nix
Labels: review me

#162 Create SECURITY.md
  SECURITY.md
Labels: review me

#159 add socket addr to Fragment Origin
  Cargo.lock
  src/jormungandr/jormungandr-lib/src/interfaces/fragment_log.rs
  src/jormungandr/jormungandr/Cargo.toml
  src/jormungandr/jormungandr/src/fragment/logs.rs
  src/jormungandr/jormungandr/src/network/bootstrap.rs
  src/jormungandr/jormungandr/src/network/mod.rs
  src/jormungandr/jormungandr/src/network/subscription.rs
Labels: review me

#161 Add example of 8 spending counters
  book/src/core-ledger-doc/api/v0.yaml
Labels: review me

#151 Implement dbsync mock with cardano node mock
  Cargo.lock
  src/vit-testing/integration-tests/src/common/mainnet_wallet_ext.rs
  src/vit-testing/integration-tests/src/common/mod.rs
  src/vit-testing/integration-tests/src/common/snapshot/mock.rs
  src/vit-testing/integration-tests/src/common/wallet.rs
  src/vit-testing/integration-tests/src/component/backend/cip_36_support.rs
  src/vit-testing/integration-tests/src/component/snapshot/local.rs
  src/vit-testing/integration-tests/src/e2e/local/active_voters_rewards.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_catalyst_toolbox.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_merge.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vit_servicing_station.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vitup.rs
  src/vit-testing/mainnet-lib/Cargo.toml
  src/vit-testing/mainnet-lib/src/blockfrost/mod.rs
  src/vit-testing/mainnet-lib/src/cardano_node/block.rs
  src/vit-testing/mainnet-lib/src/cardano_node/in_memory.rs
  src/vit-testing/mainnet-lib/src/cardano_node/ledger.rs
  src/vit-testing/mainnet-lib/src/cardano_node/mod.rs
  src/vit-testing/mainnet-lib/src/cardano_node/settings.rs
  src/vit-testing/mainnet-lib/src/cardano_node/transaction.rs
  src/vit-testing/mainnet-lib/src/db_sync/in_memory.rs
  src/vit-testing/mainnet-lib/src/db_sync/mod.rs
  src/vit-testing/mainnet-lib/src/lib.rs
  src/vit-testing/mainnet-lib/src/network/mod.rs
  src/vit-testing/mainnet-lib/src/wallet/mod.rs
  src/vit-testing/mainnet-lib/src/wallet/registration.rs
  src/vit-testing/mainnet-tools/Cargo.toml
  src/vit-testing/mainnet-tools/src/bin/blockfrost-catalyst.rs
  src/vit-testing/mainnet-tools/src/bin/fake_snapshot_tool.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/mock/mod.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/mod.rs
  src/vit-testing/mainnet-tools/src/cardano_cli/wrapper/mod.rs
  src/vit-testing/mainnet-tools/src/lib.rs
  src/voting-tools-rs/src/logic.rs
  src/voting-tools-rs/src/model/mod.rs
  src/voting-tools-rs/src/testing/functional/mod.rs
  src/voting-tools-rs/src/testing/test_api/fake.rs
Labels: review me

#147 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: review me

#169 Update VoteCast building procedure
  Cargo.lock
  src/chain-wallet-libs/bindings/wallet-core/src/tx_builder.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/utils.rs
  src/chain-wallet-libs/wallet/src/transaction/builder.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/networking/p2p/public_traffic.rs
Labels: review me

#156 Improve node config builder
  src/catalyst-toolbox/catalyst-toolbox/src/vote_check/mod.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/starter/params/builder.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/context.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/bft/start_node.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/block.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/mempool.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/networking/testnet.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/non_functional/bootstrap.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/non_functional/compatibility.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/startup.rs
  src/jormungandr/testing/mjolnir/src/mjolnir_lib/bootstrap/scenario/mod.rs
Labels: review me

#168 Adds code coverage workflow to CI
  .github/workflows/ci-tests-n-coverage.yml
  README.md
Labels: review me

#165 use nightly in devshell
  nix/automation/devshells.nix
  nix/lib/toolchains.nix
Labels: review me

#174 Refactor SpendingCounter, replace Vec usage with array
  src/chain-libs/chain-impl-mockchain/src/account.rs
  src/chain-libs/chain-impl-mockchain/src/accounting/account/spending.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/recovery.rs
  src/chain-wallet-libs/bindings/wallet-core/src/c/mod.rs
  src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
  src/chain-wallet-libs/wallet/src/account.rs
  src/chain-wallet-libs/wallet/tests/account.rs
  src/jormungandr/jormungandr-lib/src/interfaces/account_state.rs
  src/jormungandr/testing/thor/src/cli/config.rs
  src/jormungandr/testing/thor/src/cli/controller.rs
  src/jormungandr/testing/thor/src/cli/error.rs
  src/jormungandr/testing/thor/src/cli/wallet_controller.rs
  src/jormungandr/testing/thor/src/wallet/account.rs
  src/jormungandr/testing/thor/src/wallet/mod.rs
  src/vit-testing/iapyx/src/controller/mod.rs
  src/vit-testing/iapyx/src/load/multi_controller.rs
  src/vit-testing/iapyx/src/wallet.rs
Labels: review me

#110 Db sync explorer
  Cargo.lock
  Cargo.toml
  book/src/core-testing-doc/api/db-sync-explorer/openapi.yaml
  book/src/core-testing-doc/api/db-sync-explorer/postman_collection.json
  src/vit-testing/db-sync-explorer/Cargo.toml
  src/vit-testing/db-sync-explorer/res/example-config.json
  src/vit-testing/db-sync-explorer/src/bin/db-sync-explorer.rs
  src/vit-testing/db-sync-explorer/src/cli.rs
  src/vit-testing/db-sync-explorer/src/config.rs
  src/vit-testing/db-sync-explorer/src/db/config.rs
  src/vit-testing/db-sync-explorer/src/db/connector.rs
  src/vit-testing/db-sync-explorer/src/db/mod.rs
  src/vit-testing/db-sync-explorer/src/db/model.rs
  src/vit-testing/db-sync-explorer/src/db/query.rs
  src/vit-testing/db-sync-explorer/src/db/schema.rs
  src/vit-testing/db-sync-explorer/src/db/types.rs
  src/vit-testing/db-sync-explorer/src/lib.rs
  src/vit-testing/db-sync-explorer/src/rest/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/context.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/api_token.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/health/handlers.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/health/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/health/routes.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/meta/handlers.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/meta/logic.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/meta/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/meta/routes.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/sync/handlers.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/sync/logic.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/sync/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/sync/routes.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/tx/handlers.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/tx/logic.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/tx/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/endpoints/tx/routes.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/errors.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/mod.rs
  src/vit-testing/db-sync-explorer/src/rest/v0/result.rs
  src/vit-testing/mainnet-lib/src/db_sync/in_memory.rs
Labels: review me

#184 Update ci_tests.yml
  .github/workflows/ci_tests.yml
Labels: review me

#188 Cancel previous CI jobs
  .github/workflows/build.yml
  .github/workflows/ci_tests.yml
Labels: review me

#189 Update wallet-js CD job
  .github/workflows/js_wallet_publish.yml
  Cargo.lock
  src/chain-wallet-libs/bindings/wallet-cordova/package.json
  src/chain-wallet-libs/bindings/wallet-cordova/plugin.xml
  src/chain-wallet-libs/bindings/wallet-cordova/tests/package.json
  src/chain-wallet-libs/bindings/wallet-cordova/tests/plugin.xml
  src/chain-wallet-libs/bindings/wallet-core/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-uniffi/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json
  src/chain-wallet-libs/chain-path-derivation/Cargo.toml
  src/chain-wallet-libs/hdkeygen/Cargo.toml
  src/chain-wallet-libs/symmetric-cipher/Cargo.toml
  src/chain-wallet-libs/wallet/Cargo.toml
Labels: review me

#193 Update build and ci_tests workflows
  .github/workflows/build.yml
  .github/workflows/ci_tests.yml
Labels: review me
