Repository input-output-hk/catalyst-core, pull requests merged in 2023-08, with the labels that each got.

#486 feat: Stage specific data | NPG-7769
  .gitignore
  containers/event-db-migrations/Earthfile
  containers/event-db-migrations/entry.sh
  src/event-db/Earthfile
  src/event-db/historic_data/fund_10.sql
  src/event-db/migrations/V1__config_tables.sql
  src/event-db/stage_data/Readme.md
  src/event-db/stage_data/dev/.gitignore
  src/event-db/stage_data/dev/00001_fund10_event.sql
  src/event-db/stage_data/dev/00002_fund10_ideascale_params.sql
  src/event-db/stage_data/local/.gitignore
  src/event-db/stage_data/preprod/.gitignore
  src/event-db/stage_data/prod/.gitignore
  src/event-db/stage_data/testnet/.gitignore
  src/event-db/stage_data/testnet/00001_fund10_event.sql
  src/event-db/stage_data/testnet/00002_fund10_ideascale_params.sql
Labels: review me

#490 feat: Audit tooling | NPG-6520
  Cargo.lock
  Cargo.toml
  src/audit/Cargo.toml
  src/audit/README.md
  src/audit/balance/Earthfile
  src/audit/balance/README.md
  src/audit/balance/entry.sh
  src/audit/balance/node_config.yaml
  src/audit/src/find/README.md
  src/audit/src/find/bin/main.rs
  src/audit/src/lib/find.rs
  src/audit/src/lib/mod.rs
  src/audit/src/lib/offline.rs
  src/audit/src/lib/recover.rs
  src/audit/src/lib/tally.rs
  src/audit/src/offline/bin/main.rs
  src/audit/src/tally/README.md
  src/audit/src/tally/bin/main.rs
  src/catalyst-toolbox/catalyst-toolbox/tests/tally/main.rs
  src/chain-libs/chain-impl-mockchain/Cargo.toml
  src/chain-libs/chain-impl-mockchain/src/vote/manager.rs
  src/tally/Cargo.toml
Labels: review me

#494 fix: Fix voting node not running snapshot importer before registration_snapshot_time | NPG-7849
  services/voting-node/voting_node/db.py
  services/voting-node/voting_node/importer.py
  services/voting-node/voting_node/tasks.py
Labels: review me

#497 fix: Catalyst-toolbox voting registration `stake_public_key` and `reward_address` encoding | NPG-7784
  src/catalyst-toolbox/catalyst-toolbox/Cargo.toml
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/dreps.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/full/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/rewards/voters.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/snapshot/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/sve_snapshot.rs
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/dreps.rs
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/voters.rs
  src/catalyst-toolbox/snapshot-lib/src/influence_cap.rs
  src/catalyst-toolbox/snapshot-lib/src/lib.rs
  src/catalyst-toolbox/snapshot-lib/src/registration.rs
  src/catalyst-toolbox/snapshot-lib/src/sve.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/handlers.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/raw_snapshot.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/snapshots/verifier.rs
  src/vit-testing/integration-tests/src/common/snapshot/result.rs
  src/vit-testing/integration-tests/src/common/snapshot/voter_hirs_asserts.rs
  src/vit-testing/integration-tests/src/common/snapshot_filter.rs
  src/vit-testing/integration-tests/src/e2e/local/active_voters_rewards.rs
  src/vit-testing/integration-tests/src/e2e/rewards/rewards_scenarios.rs
  src/vit-testing/integration-tests/src/e2e/rewards/voter_rewards.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vit_servicing_station.rs
  src/vit-testing/mainnet-tools/src/snapshot/convert.rs
  utilities/ideascale-importer/ideascale_importer/cli/snapshot.py
  utilities/ideascale-importer/ideascale_importer/db/__init__.py
  utilities/ideascale-importer/ideascale_importer/snapshot_importer.py
Labels: do not merge yet

#502 feat: Update ideascale-importer config loading | NPG-7499
  Earthfile
  book/src/07_web_api/openapi/core_backend_api.yaml
  containers/dev-local/docker-compose.yml
  services/voting-node/docker-compose.yml
  services/voting-node/entry.sh
  services/voting-node/voting_node/importer.py
  src/event-db/stage_data/dev/00002_fund10_ideascale_params.sql
  src/event-db/stage_data/testnet/00002_fund10_ideascale_params.sql
  utilities/ideascale-importer/Earthfile
  utilities/ideascale-importer/ideascale-importer-config.json
  utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
  utilities/ideascale-importer/ideascale_importer/db/__init__.py
  utilities/ideascale-importer/ideascale_importer/db/models.py
  utilities/ideascale-importer/ideascale_importer/ideascale/importer.py
Labels: review me

#505 feat: Added different logs formatting for cat-data-service | NPG-5779
  src/cat-data-service/Cargo.toml
  src/cat-data-service/README.md
  src/cat-data-service/src/cli.rs
  src/cat-data-service/src/logger.rs
  src/cat-data-service/src/settings.rs
Labels: review me

#506 feat: Wallet, registrations, and voting power | NPG-5768
  services/voting-node/voting_node/committee.py
  services/voting-node/voting_node/db.py
  services/voting-node/voting_node/importer.py
  services/voting-node/voting_node/jcli.py
  services/voting-node/voting_node/models/__init__.py
  services/voting-node/voting_node/models/committee.py
  services/voting-node/voting_node/models/token.py
  services/voting-node/voting_node/node.py
  services/voting-node/voting_node/service.py
  services/voting-node/voting_node/storage.py
  services/voting-node/voting_node/tasks.py
  services/voting-node/voting_node/utils.py
Labels: review me

#509 feat: Update pydantic to v2 | NPG-0000
  services/voting-node/poetry.lock
  services/voting-node/pyproject.toml
  services/voting-node/voting_node/models/__init__.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me, dependencies

#510 feat: Add initial version of the reviews importer | NPG-7896
  utilities/ideascale-importer/ideascale_importer/app.py
  utilities/ideascale-importer/ideascale_importer/cli/reviews.py
  utilities/ideascale-importer/ideascale_importer/gvc.py
  utilities/ideascale-importer/ideascale_importer/ideascale/client.py
  utilities/ideascale-importer/ideascale_importer/ideascale/importer.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer.py
  utilities/ideascale-importer/ideascale_importer/snapshot_importer.py
  utilities/ideascale-importer/ideascale_importer/utils.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me

#514 fix: Update dev dependencies for lxml | NPG-0000
  utilities/ideascale-importer/Earthfile
Labels: review me

#515 build: updates nixpkgs to include latest rustc | NPG-0000
  .prettierrc
  flake.lock
  nix/automation/devshells.nix
Labels: review me

#517 fix: Use zlib1g-dev instead of lib32z-dev | NPG-0000
  services/voting-node/Earthfile
  utilities/ideascale-importer/Earthfile
Labels: review me

#520 feat: update README, remove GraphQL container | NPG-7948
  .gitignore
  Earthfile
  Makefiles/db.toml
  README.md
  containers/dev-local/docker-compose.yml
  containers/event-db-graphql/Earthfile
  containers/event-db-graphql/entry.sh
  services/voting-node/docker-compose.yml
  src/event-db/setup/dev-db.docker-compose.yml
Labels: review me

#522 feat: Snapshot registration data | NPG-5768
  services/voting-node/poetry.lock
  services/voting-node/poetry.toml
  services/voting-node/pyproject.toml
  services/voting-node/tests/__init__.py
  services/voting-node/tests/leader0/__init__.py
  services/voting-node/tests/leader0/test_schedule.py
  services/voting-node/voting_node/db.py
  services/voting-node/voting_node/models/__init__.py
  services/voting-node/voting_node/tasks.py
Labels: review me

#525 build: adds missing build-time deps to voting-node | NPG-0000
  services/voting-node/Earthfile
Labels: review me

#524 feat(voting-tools-rs): Add CLI option to enable mutiple delegations in CIP-36 registrations. | NPG-0000
  Cargo.lock
  src/vit-testing/mainnet-tools/src/snapshot/convert.rs
  src/voting-tools-rs/Cargo.toml
  src/voting-tools-rs/diesel.toml
  src/voting-tools-rs/src/bin/snapshot_tool.rs
  src/voting-tools-rs/src/cli.rs
  src/voting-tools-rs/src/data/arbitrary.rs
  src/voting-tools-rs/src/data/cbor.rs
  src/voting-tools-rs/src/data/crypto2/pub_key.rs
  src/voting-tools-rs/src/data/crypto2/sig.rs
  src/voting-tools-rs/src/data/hash.rs
  src/voting-tools-rs/src/data/mod.rs
  src/voting-tools-rs/src/data_provider.rs
  src/voting-tools-rs/src/db/mod.rs
  src/voting-tools-rs/src/db/queries/mod.rs
  src/voting-tools-rs/src/db/queries/stake_value.rs
  src/voting-tools-rs/src/db/queries/vote_registrations.rs
  src/voting-tools-rs/src/db/schema.rs
  src/voting-tools-rs/src/db/types.rs
  src/voting-tools-rs/src/db/utils.rs
  src/voting-tools-rs/src/error/mod.rs
  src/voting-tools-rs/src/lib.rs
  src/voting-tools-rs/src/logic/args.rs
  src/voting-tools-rs/src/logic/mod.rs
  src/voting-tools-rs/src/testing/e2e/Readme.md
  src/voting-tools-rs/src/testing/e2e/create_tables.sql
  src/voting-tools-rs/src/testing/e2e/init.rs
  src/voting-tools-rs/src/testing/e2e/mod.rs
  src/voting-tools-rs/src/testing/e2e/reference_tx_in.json
  src/voting-tools-rs/src/testing/e2e/reference_tx_meta.json
  src/voting-tools-rs/src/testing/e2e/reference_tx_out.json
  src/voting-tools-rs/src/testing/e2e/snapshots/voting_tools_rs__testing__reference__simple_query.snap
  src/voting-tools-rs/src/testing/mod.rs
  src/voting-tools-rs/src/testing/test_api/fake.rs
  src/voting-tools-rs/src/testing/test_api/mod.rs
  src/voting-tools-rs/src/testing/test_api/output_assertions.rs
  src/voting-tools-rs/src/testing/vectors/cip15.rs
  src/voting-tools-rs/src/testing/vectors/mod.rs
  src/voting-tools-rs/src/validation/cbor.rs
  src/voting-tools-rs/src/validation/mod.rs
  src/voting-tools-rs/src/validation/tests.rs
  src/voting-tools-rs/src/verification/verify.rs
Labels: enhancement, review me

#528 fix: Review's importer processing logic fixing | NPG-7896
  src/event-db/stage_data/dev/00002_fund10_ideascale_params.sql
  src/event-db/stage_data/testnet/00002_fund10_ideascale_params.sql
  utilities/ideascale-importer/ideascale_importer/reviews_importer/importer.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/prepare.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/tools/importer.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/tools/postprocessor.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/types/models.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/utils.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me

#527 fix: Upgrade lxml version | NPG-000
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me

#531 feat: Add Voting Node to mdbook with Earthly | NPG-5888
  Earthfile
  book/src/09_python_api/00.md
  book/src/09_python_api/voting-node-api.md
  containers/book/Earthfile
  containers/book/README.md
  containers/book/build-db-diagrams.sh
  containers/book/docker-compose.yml
  services/voting-node/voting_node/__init__.py
Labels: review me

#535 fix: Lovelace rounding and docs catalyst toolbox | NPG-000
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/sve_snapshot.rs
  src/catalyst-toolbox/snapshot-lib/src/sve.rs
Labels: review me

#536 fix: Update lxml for voting node | NPG-000
  services/voting-node/poetry.lock
  services/voting-node/pyproject.toml
Labels: review me

#534 fix(catalyst-toolbox): Fix error when purpose is null. | NPG-0000
  containers/event-db-migrations/entry.sh
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/snapshot/mod.rs
  src/catalyst-toolbox/catalyst-toolbox/src/rewards/voters.rs
  src/catalyst-toolbox/snapshot-lib/src/lib.rs
  src/catalyst-toolbox/snapshot-lib/src/registration.rs
  src/catalyst-toolbox/snapshot-lib/src/voter_hir.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/raw_snapshot.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/snapshot.rs
  src/vit-testing/mainnet-tools/src/snapshot/convert.rs
  src/vit-testing/vitup/src/mode/mock/snapshot.rs
  utilities/snapshot-check/compare_snapshot.py
Labels: review me

#539 chore: Enable prometheus metrics in jormungandr by default | NPG-000
  src/jormungandr/jormungandr/Cargo.toml
Labels: review me

#542 chore: Observability improvements to node logs and metrics | NPG-7984
  src/jormungandr/jormungandr/src/fragment/pool.rs
  src/jormungandr/jormungandr/src/metrics/backends/prometheus_exporter.rs
Labels: review me

#544 chore: Necessary fixes to earthly book building | NPG-000
  containers/book/Earthfile
  containers/book/build-db-diagrams.sh
  containers/book/build-mdbook.sh
Labels: review me

#540 feat: Review's importer test | NPG-8040
  .github/workflows/rust.yml
  src/cat-data-service/src/service/mod.rs
  src/cat-data-service/src/service/v0/fund.rs
  src/cat-data-service/src/service/v1/event/ballots.rs
  src/cat-data-service/src/service/v1/event/mod.rs
  src/cat-data-service/src/service/v1/event/objective/ballots.rs
  src/cat-data-service/src/service/v1/event/objective/mod.rs
  src/cat-data-service/src/service/v1/event/objective/proposal/ballot.rs
  src/cat-data-service/src/service/v1/event/objective/proposal/mod.rs
  src/cat-data-service/src/service/v1/event/objective/proposal/review.rs
  src/cat-data-service/src/service/v1/event/objective/review_type.rs
  src/cat-data-service/src/service/v1/jorm_mock/mod.rs
  src/cat-data-service/src/service/v1/registration.rs
  src/cat-data-service/src/service/v1/search.rs
  src/event-db/docker-compose.yml
  src/event-db/src/queries/event/mod.rs
  src/event-db/src/queries/search.rs
  src/event-db/stage_data/dev/00001_testfund_event.sql
  src/event-db/stage_data/dev/00002_testfund_ideascale_params.sql
  utilities/ideascale-importer/Earthfile
  utilities/ideascale-importer/ideascale_importer/cli/reviews.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/importer.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/tools/importer.py
  utilities/ideascale-importer/ideascale_importer/reviews_importer/processing/types/models.py
  utilities/ideascale-importer/ideascale_importer/tests/pa.csv
  utilities/ideascale-importer/ideascale_importer/tests/reviews_importer_test.py
  utilities/ideascale-importer/ideascale_importer/tests/utils_test.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me
