Repository input-output-hk/catalyst-core, pull requests merged in 2023-01, with the labels that each got.

#195 Update README.md
  README.md
Labels: review me

#183 implement new snapshot/create operation in mock
  Cargo.lock
  src/vit-servicing-station/vit-servicing-station-tests/src/common/raw_snapshot.rs
  src/vit-testing/integration-tests/src/common/snapshot/mod.rs
  src/vit-testing/integration-tests/src/common/snapshot/result.rs
  src/vit-testing/integration-tests/src/component/backend/cip_36_support.rs
  src/vit-testing/integration-tests/src/component/snapshot/local.rs
  src/vit-testing/integration-tests/src/e2e/local/active_voters_rewards.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_catalyst_toolbox.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_merge.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vit_servicing_station.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vitup.rs
  src/vit-testing/mainnet-lib/Cargo.toml
  src/vit-testing/mainnet-lib/src/cardano_node/block.rs
  src/vit-testing/mainnet-lib/src/cardano_node/in_memory.rs
  src/vit-testing/mainnet-lib/src/cardano_node/ledger.rs
  src/vit-testing/mainnet-lib/src/cardano_node/mod.rs
  src/vit-testing/mainnet-lib/src/db_sync/in_memory.rs
  src/vit-testing/mainnet-lib/src/lib.rs
  src/vit-testing/mainnet-lib/src/network/mod.rs
  src/vit-testing/mainnet-lib/src/network/snapshot.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/builder.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/mod.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/template/actor.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/template/arbitrary.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/template/external_providers.rs
  src/vit-testing/mainnet-lib/src/network/wallet_state/template/mod.rs
  src/vit-testing/mainnet-tools/Cargo.toml
  src/vit-testing/mainnet-tools/src/bin/snapshot-wormhole.rs
  src/vit-testing/mainnet-tools/src/lib.rs
  src/vit-testing/mainnet-tools/src/snapshot/convert.rs
  src/vit-testing/mainnet-tools/src/snapshot/mod.rs
  src/vit-testing/mainnet-tools/src/snapshot/wormhole/command.rs
  src/vit-testing/mainnet-tools/src/snapshot/wormhole/config.rs
  src/vit-testing/mainnet-tools/src/snapshot/wormhole/mod.rs
  src/vit-testing/vitup/Cargo.toml
  src/vit-testing/vitup/docker/mock/Dockerfile
  src/vit-testing/vitup/src/config/builder.rs
  src/vit-testing/vitup/src/config/initials/mod.rs
  src/vit-testing/vitup/src/config/initials/snapshot.rs
  src/vit-testing/vitup/src/config/mod.rs
  src/vit-testing/vitup/src/mode/mock/mock_state.rs
  src/vit-testing/vitup/src/mode/mock/rest/admin.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/handlers.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/routes.rs
  src/vit-testing/vitup/src/mode/mock/snapshot.rs
  src/voting-tools-rs/src/testing/functional/mod.rs
Labels: review me

#202 add comments for clarity
  Cargo.lock
  src/jormungandr/jormungandr/src/network/p2p/comm/peer_map.rs
  src/jormungandr/jormungandr/src/network/subscription.rs
Labels: review me

#200 Make timestamps BIGINT and some other adjustments
  src/election-db/migrations/2022-12-01-043118_vit-ss/up.sql
Labels: review me

#197 Document vitup mock
  book/src/SUMMARY.md
  book/src/api/vit-testing-mock-farm-v0.md
  book/src/api/vit-testing-mock-v0.md
  book/src/core-testing-doc/api/vitup/mock/Mock.postman_collection.json
  book/src/core-testing-doc/api/vitup/mock/v0.yaml
  book/src/core-testing-doc/vitup/mock.md
  src/vit-testing/vitup/src/mode/mock/ledger_state.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/handlers.rs
  src/vit-testing/vitup/src/mode/mock/rest/control/routes.rs
  src/vit-testing/vitup/src/mode/mock/rest/mod.rs
Labels: documentation, review me

#198 use stable devshell for now
  .prettierrc
  flake.lock
  nix/automation/devshells.nix
Labels: review me

#208 [Doics] removed not used configuration parameter (ideascale).
  book/src/core-testing-doc/vitup/configuration.md
  book/src/core-testing-doc/vitup/data_generation.md
  book/src/core-testing-doc/vitup/data_generation/reset.md
  book/src/core-testing-doc/vitup/data_generation/snapshot.md
  book/src/core-testing-doc/vitup/mock.md
  src/vit-testing/db-sync-explorer/config-snapshot.json
  src/vit-testing/integration-tests/src/component/backend/cip_36_support.rs
  src/vit-testing/mainnet-lib/src/network/snapshot.rs
  src/vit-testing/vitup/example/mock/config.yaml
  src/vit-testing/vitup/example/mock/https.yaml
  src/vit-testing/vitup/src/mode/mock/config.rs
  src/vit-testing/vitup/src/mode/mock/farm/controller.rs
  src/vit-testing/vitup/src/mode/mock/snapshot.rs
  src/vit-testing/vitup/tests/mock/soak.rs
  src/vit-testing/vitup/tests/mock/startup.rs
Labels: documentation

#207 Update PR template, add dependecies section
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, review me

#154 Npg 3427 voting key saturation endpoint tests
  src/vit-servicing-station/vit-servicing-station-tests/src/common/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/rest/voting_key_saturation.rs
Labels: review me

#212 Dedup 7
  Cargo.lock
  Cargo.toml
  src/chain-libs/chain-vote/Cargo.toml
  src/jortestkit/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-cli/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-tests/Cargo.toml
  src/vit-testing/iapyx/Cargo.toml
  src/vit-testing/integration-tests/Cargo.toml
  src/vit-testing/mainnet-tools/Cargo.toml
  src/vit-testing/scheduler-service-lib/Cargo.toml
  src/vit-testing/snapshot-trigger-service/Cargo.toml
  src/vit-testing/vitup/Cargo.toml
  src/voting-tools-rs/src/model/mod.rs
Labels: review me

#220 Revert "Dedup 7"
  Cargo.lock
  Cargo.toml
  src/chain-libs/chain-vote/Cargo.toml
  src/jortestkit/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-cli/Cargo.toml
  src/vit-servicing-station/vit-servicing-station-tests/Cargo.toml
  src/vit-testing/iapyx/Cargo.toml
  src/vit-testing/integration-tests/Cargo.toml
  src/vit-testing/mainnet-tools/Cargo.toml
  src/vit-testing/scheduler-service-lib/Cargo.toml
  src/vit-testing/snapshot-trigger-service/Cargo.toml
  src/vit-testing/vitup/Cargo.toml
  src/voting-tools-rs/src/model/mod.rs
Labels: review me

#204 build: makes containers easier to troubleshoot
  nix/jormungandr/containers.nix
  nix/jormungandr/operables.nix
  nix/lib/lib.nix
  nix/vit-servicing-station/containers.nix
  nix/vit-servicing-station/operables.nix
Labels: review me

#206 refactor: switch to gov account
  .github/workflows/nix.yml
  flake.nix
  nix/lib/constants.nix
Labels: review me

#213 point dockerfile to main
  src/vit-testing/vitup/docker/mock/Dockerfile
Labels: review me

#214 Remove transaction's expiration date filed validation
  src/catalyst-toolbox/catalyst-toolbox/src/recovery/tally.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/check.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/ledger.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  src/chain-libs/chain-impl-mockchain/src/testing/e2e/spending_counter_lanes.rs
  src/chain-libs/chain-impl-mockchain/src/testing/ledger.rs
  src/chain-libs/chain-impl-mockchain/src/testing/scenario/controller.rs
  src/chain-libs/chain-impl-mockchain/src/transaction/transaction.rs
  src/chain-wallet-libs/bindings/wallet-core/src/tx_builder.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
  src/jormungandr/jormungandr-lib/src/interfaces/fragments_processing_summary.rs
  src/jormungandr/jormungandr/src/fragment/pool.rs
Labels: review me

#192 Add rust style guide
  .std/automation/devshells/dev/shell-profile
  book/src/rust/rust_style_guide.md
  src/chain-libs/chain-impl-mockchain/src/stake/controlled.rs
Labels: review me

#234 Fix integration tests
  book/src/core-ledger-doc/jcli/key.md
  book/src/core-ledger-doc/testing/automation.md
  src/catalyst-toolbox/README.md
  src/jormungandr/jcli/src/jcli_lib/certificate/new_stake_pool_registration.rs
  src/jormungandr/testing/jormungandr-automation/src/jcli/api/key.rs
  src/jormungandr/testing/jormungandr-automation/src/jcli/command/rest/v0/block.rs
  src/jormungandr/testing/jormungandr-automation/src/jcli/command/rest/v0/mod.rs
  src/jormungandr/testing/jormungandr-automation/src/jcli/command/rest/v0/node.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/address/account.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/address/info.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/address/single.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/key/from_bytes.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/key/generate.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/key/to_bytes.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/key/to_public.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/rest/host.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jcli/transaction/input.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/mod.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/persistent_log.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/transactions.rs
  src/vit-testing/integration-tests/src/common/snapshot/controller.rs
  src/vit-testing/integration-tests/src/common/snapshot/mock.rs
  src/vit-testing/integration-tests/src/common/snapshot/mod.rs
  src/vit-testing/integration-tests/src/common/snapshot_filter.rs
Labels: review me

#228 Update node metrics
  src/jormungandr/jormungandr-lib/src/interfaces/stats.rs
  src/jormungandr/jormungandr/src/fragment/pool.rs
  src/jormungandr/jormungandr/src/metrics/backends/prometheus_exporter.rs
  src/jormungandr/jormungandr/src/metrics/backends/simple_counter.rs
  src/jormungandr/jormungandr/src/metrics/mod.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/mempool.rs
  src/vit-testing/vitup/src/mode/mock/congestion.rs
  src/vit-testing/vitup/src/mode/mock/mock_state.rs
Labels: review me

#232 Update mempool functionality, get rid of the transaction's expiration date field processing
  src/jormungandr/jormungandr/src/fragment/pool.rs
  src/jormungandr/jormungandr/src/fragment/process.rs
  src/jormungandr/jormungandr/src/fragment/selection.rs
  src/jormungandr/jormungandr/src/lib.rs
  src/jormungandr/testing/jormungandr-automation/src/jormungandr/verifier/fragment_log.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/bft/mempool/v0.rs
  src/jormungandr/testing/jormungandr-integration-tests/src/jormungandr/mempool.rs
Labels: review me

#237 Remove spending counter from Vote Cast transactions
  Cargo.lock
  src/chain-libs/chain-impl-mockchain/Cargo.toml
  src/chain-libs/chain-impl-mockchain/src/accounting/account/account_state.rs
  src/chain-libs/chain-impl-mockchain/src/accounting/account/mod.rs
  src/chain-libs/chain-impl-mockchain/src/accounting/account/spending.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/check.rs
  src/chain-libs/chain-impl-mockchain/src/ledger/ledger.rs
  src/chain-libs/chain-impl-mockchain/src/multisig/ledger.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/package.json
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
Labels: review me

#218 Refactor and speed up ci tests
  .config/nextest.toml
  .github/workflows/build.yml
  .github/workflows/ci-tests-n-coverage.yml
  .github/workflows/ci_tests.yml
Labels: review me

#245 Fix wallet-js interface, fix bug with the private casting
  Cargo.lock
  src/chain-wallet-libs/bindings/wallet-wasm-js/Cargo.toml
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package_test.json
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/certificates/vote_cast.rs
Labels: review me

#247 ci: Add Postgres container service for vit-ss tests
  .github/workflows/ci-tests-n-coverage.yml
  .github/workflows/ci_tests.yml
Labels: review me

#248 Windows build cache only on merge to main
  .github/workflows/build.yml
Labels: review me

#211 Npg 1371 voter rewards e2e tests
  Cargo.lock
  src/vit-servicing-station/vit-servicing-station-tests/Cargo.toml
  src/vit-testing/integration-tests/Cargo.toml
  src/vit-testing/integration-tests/src/common/snapshot/controller.rs
  src/vit-testing/integration-tests/src/e2e/mod.rs
  src/vit-testing/integration-tests/src/e2e/rewards/mod.rs
  src/vit-testing/integration-tests/src/e2e/rewards/voter_rewards.rs
Labels: draft

#227 Feature/npg 3367 test delegator endpoint
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/path.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/clients/rest/raw.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/snapshot.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/tests/snapshots/snapshot.rs
  src/vit-testing/integration-tests/src/integration/from_snapshot_to_vit_servicing_station.rs
  src/vit-testing/vitup/src/mode/standard/controllers/vit_station/controller.rs
Labels: review me

#255 refactor(ci): naming
  .github/workflows/branch-delete-cleanup.yml
  .github/workflows/gh-pages.yml
  .github/workflows/mdlint-changed.yml
  .github/workflows/rust.yml
Labels: review me

#249 Update wallet js tx building process, refactor WitnessBuilder
  src/catalyst-toolbox/catalyst-toolbox/src/recovery/tally.rs
  src/chain-libs/chain-impl-mockchain/src/transaction/witness.rs
  src/chain-wallet-libs/bindings/wallet-core/src/tx_builder.rs
  src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/js-test/test/vote_cast.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.d.ts
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js
  src/chain-wallet-libs/bindings/wallet-wasm-js/src/lib.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/tests/certificates/vote_cast.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/tests/certificates/vote_plan.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/tests/lib.rs
  src/chain-wallet-libs/wallet/src/account.rs
  src/chain-wallet-libs/wallet/src/transaction/builder.rs
  src/chain-wallet-libs/wallet/src/transaction/mod.rs
  src/chain-wallet-libs/wallet/src/transaction/witness_builder.rs
  src/chain-wallet-libs/wallet/tests/account.rs
Labels: enhancement, review me

#256 Fix vitup log level
  src/vit-testing/vitup/src/cli/start/advanced.rs
  src/vit-testing/vitup/src/cli/start/quick.rs
Labels: review me
