Repository input-output-hk/catalyst-core, pull requests merged in 2023-03, with the labels that each got.

#280 ci: NPG-5347 Add security scorecards
  .github/workflows/scorecards-analysis.yml
Labels: review me

#276 feat: NPG-5359 Add new dreps argument for snapshot tool
  Cargo.lock
  book/src/07_web_api/openapi/vitss_v0.yaml
  src/catalyst-toolbox/catalyst-toolbox/src/bin/cli/snapshot/mod.rs
  src/catalyst-toolbox/snapshot-lib/Cargo.toml
  src/catalyst-toolbox/snapshot-lib/src/lib.rs
  src/catalyst-toolbox/snapshot-lib/src/registration.rs
  src/catalyst-toolbox/snapshot-lib/src/voting_group.rs
  src/chain-wallet-libs/bindings/wallet-wasm-js/js/package.json
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/handlers.rs
  src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs
  src/vit-servicing-station/vit-servicing-station-tests/src/common/raw_snapshot.rs
  src/vit-testing/integration-tests/src/common/reps.rs
  src/vit-testing/mainnet-lib/src/network/snapshot.rs
  src/vit-testing/mainnet-tools/src/snapshot/convert.rs
  src/vit-testing/vitup/src/mode/mock/rest/admin.rs
Labels: review me

#284 feat: NPG-5482 Initialize "Catalyst Event Data" service
  Cargo.lock
  Cargo.toml
  src/cat-data-service/Cargo.toml
  src/cat-data-service/README.md
  src/cat-data-service/src/cli.rs
  src/cat-data-service/src/logger.rs
  src/cat-data-service/src/main.rs
  src/cat-data-service/src/service/mod.rs
  src/cat-data-service/src/service/v0/mod.rs
  src/cat-data-service/src/service/v0/snapshot/delegator.rs
  src/cat-data-service/src/service/v0/snapshot/mod.rs
  src/cat-data-service/src/service/v0/snapshot/voter.rs
  src/cat-data-service/src/settings.rs
Labels: review me

#261 feat: NPG-1368 drep incentives tests
  src/vit-testing/integration-tests/src/e2e/rewards/drep_rewards.rs
  src/vit-testing/integration-tests/src/e2e/rewards/mod.rs
Labels: review me

#288 fix: Minor changes to migrations
  Cargo.lock
  src/event-db/migrations/V2__event_tables.sql
  src/event-db/migrations/V9__catalyst_automation.sql
Labels: bug, review me

#290 fix: Add extra snapshot to sve_snapshot.py
  utilities/sve-snapshot/sve_snapshot.py
Labels: review me

#291 feat: Catalyst data service new endpoints
  Cargo.lock
  src/cat-data-service/Cargo.toml
  src/cat-data-service/src/cli.rs
  src/cat-data-service/src/db/fund.rs
  src/cat-data-service/src/db/mod.rs
  src/cat-data-service/src/db/proposal.rs
  src/cat-data-service/src/db/snapshot.rs
  src/cat-data-service/src/main.rs
  src/cat-data-service/src/service/mod.rs
  src/cat-data-service/src/service/v0/chalenges.rs
  src/cat-data-service/src/service/v0/fund.rs
  src/cat-data-service/src/service/v0/mod.rs
  src/cat-data-service/src/service/v0/proposals.rs
  src/cat-data-service/src/service/v0/reviews.rs
  src/cat-data-service/src/service/v0/snapshot.rs
  src/cat-data-service/src/service/v0/snapshot/delegator.rs
  src/cat-data-service/src/service/v0/snapshot/mod.rs
  src/cat-data-service/src/service/v0/snapshot/voter.rs
Labels: review me

#242 feat: Voting Node Service - Build Block0
  .dockerignore
  .gitignore
  Makefile.toml
  Makefiles/docker.toml
  docker/catalyst-core-base.dockerfile
  docker/jormungandr.dockerfile
  docker/vit-servicing-station.dockerfile
  docker/voting-node.dockerfile
  services/voting-node/.dockerignore
  services/voting-node/.gitignore
  services/voting-node/VERSION
  services/voting-node/development.md
  services/voting-node/docker-compose.yml
  services/voting-node/extras/datasource.yml
  services/voting-node/extras/otel-collector.yaml
  services/voting-node/extras/prometheus.yml
  services/voting-node/extras/tempo-local.yaml
  services/voting-node/poetry.lock
  services/voting-node/poetry.toml
  services/voting-node/pyproject.toml
  services/voting-node/voting_node/__init__.py
  services/voting-node/voting_node/api.py
  services/voting-node/voting_node/config.py
  services/voting-node/voting_node/db.py
  services/voting-node/voting_node/jcli.py
  services/voting-node/voting_node/jormungandr.py
  services/voting-node/voting_node/logs.py
  services/voting-node/voting_node/main.py
  services/voting-node/voting_node/models.py
  services/voting-node/voting_node/service.py
  services/voting-node/voting_node/tasks.py
  services/voting-node/voting_node/templates.py
  services/voting-node/voting_node/utils.py
  src/jormungandr/ci/docker/Dockerfile
  src/jormungandr/docker/Dockerfile
  src/jormungandr/docker/alpine/Dockerfile
  src/vit-servicing-station/docker/master/Dockerfile
Labels: review me

#293 fix: Vitup mock broken link
  book/src/03_core_testing/api/vitup/mock-farm/mock_farm_postman_collection.json
  book/src/03_core_testing/api/vitup/mock-farm/v0.yaml
  book/src/03_core_testing/api/vitup/mock/mock_postman_collection.json
  book/src/03_core_testing/vitup/mock.md
  book/src/03_core_testing/vitup/mock_farm.md
Labels: review me

#295 test(integration-test): NPG-1368 More drep tests
  src/vit-testing/integration-tests/src/e2e/rewards/mod.rs
  src/vit-testing/integration-tests/src/e2e/rewards/rewards_scenarios.rs
Labels: review me

#294 feat: Voting power snapshot automation script
  utilities/ideascale-importer/.gitignore
  utilities/ideascale-importer/.python-version
  utilities/ideascale-importer/README.md
  utilities/ideascale-importer/docs/ideascale.md
  utilities/ideascale-importer/docs/snapshot.md
  utilities/ideascale-importer/ideascale-importer-config.json
  utilities/ideascale-importer/ideascale_importer/__init__.py
  utilities/ideascale-importer/ideascale_importer/__main__.py
  utilities/ideascale-importer/ideascale_importer/cli/__init__.py
  utilities/ideascale-importer/ideascale_importer/cli/db.py
  utilities/ideascale-importer/ideascale_importer/cli/ideascale.py
  utilities/ideascale-importer/ideascale_importer/cli/snapshot.py
  utilities/ideascale-importer/ideascale_importer/db/__init__.py
  utilities/ideascale-importer/ideascale_importer/db/models.py
  utilities/ideascale-importer/ideascale_importer/gvc/__init__.py
  utilities/ideascale-importer/ideascale_importer/gvc/client.py
  utilities/ideascale-importer/ideascale_importer/ideascale/__init__.py
  utilities/ideascale-importer/ideascale_importer/ideascale/client.py
  utilities/ideascale-importer/ideascale_importer/ideascale/importer/__init__.py
  utilities/ideascale-importer/ideascale_importer/ideascale/importer/config.py
  utilities/ideascale-importer/ideascale_importer/ideascale/importer/db_mapper.py
  utilities/ideascale-importer/ideascale_importer/snapshot_importer/__init__.py
  utilities/ideascale-importer/ideascale_importer/snapshot_importer/config.py
  utilities/ideascale-importer/ideascale_importer/snapshot_importer/importer.py
  utilities/ideascale-importer/ideascale_importer/tests/__init__.py
  utilities/ideascale-importer/ideascale_importer/tests/utils_test.py
  utilities/ideascale-importer/ideascale_importer/utils.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/poetry.toml
  utilities/ideascale-importer/pyproject.toml
  utilities/ideascale-importer/requirements.txt
  utilities/ideascale-importer/snapshot-importer-example-config.json
  utilities/ideascale-importer/src/db/__init__.py
  utilities/ideascale-importer/src/main.py
  utilities/ideascale-importer/src/utils.py
Labels: review me

#297 fix: Serde empty annotations bug
  src/vit-testing/vitup/src/mode/service/manager/file_lister.rs
Labels: review me

#289 feat: Voting node service deploy leaders
  docker/voting-node.dockerfile
  services/voting-node/development.md
  services/voting-node/docker-compose.yml
  services/voting-node/poetry.lock
  services/voting-node/pyproject.toml
  services/voting-node/voting_node/config.py
  services/voting-node/voting_node/db.py
  services/voting-node/voting_node/jcli.py
  services/voting-node/voting_node/main.py
  services/voting-node/voting_node/models.py
  services/voting-node/voting_node/service.py
  services/voting-node/voting_node/tasks.py
  services/voting-node/voting_node/templates.py
  services/voting-node/voting_node/utils.py
Labels: do not review yet

#300 feat: NPG-5482 Connect EventDB to the service, add db queries
  Cargo.lock
  src/cat-data-service/Cargo.toml
  src/cat-data-service/src/cli.rs
  src/cat-data-service/src/db/mod.rs
  src/cat-data-service/src/db/snapshot.rs
  src/cat-data-service/src/main.rs
  src/cat-data-service/src/service/mod.rs
  src/cat-data-service/src/service/v0/chalenges.rs
  src/cat-data-service/src/service/v0/fund.rs
  src/cat-data-service/src/service/v0/mod.rs
  src/cat-data-service/src/service/v0/proposals.rs
  src/cat-data-service/src/service/v0/reviews.rs
  src/cat-data-service/src/service/v0/snapshot.rs
  src/cat-data-service/src/settings.rs
  src/cat-data-service/src/state.rs
  src/event-db/Cargo.toml
  src/event-db/src/lib.rs
  src/event-db/src/queries/mod.rs
  src/event-db/src/queries/snapshot.rs
  src/event-db/src/schema_check.rs
  src/event-db/src/types/mod.rs
  src/event-db/src/types/snapshot.rs
  src/event-db/src/types/utils.rs
Labels: review me

#303 feat: Add 'ideascale-importer' script to ideascale_importer package
  utilities/ideascale-importer/README.md
  utilities/ideascale-importer/ideascale_importer/__main__.py
  utilities/ideascale-importer/ideascale_importer/app.py
  utilities/ideascale-importer/poetry.lock
  utilities/ideascale-importer/pyproject.toml
Labels: review me
